# Agregar task-service al compose
services:
  # ... servicios existentes
  
  task-service:
    build:
      context: ./services/task-service
      dockerfile: Dockerfile.dev
    container_name: task-manager-task-service
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
      PORT: 3002
      DATABASE_URL: postgresql://task_user:task_password@task-db:5432/task_db
      REDIS_URL: redis://redis:6379
      REDIS_PREFIX: "tasks:"
      AUTH_SERVICE_URL: "http://auth-service:3001"
      JWT_SECRET: "dev-jwt-secret-super-secure-for-development-only-minimum-64-characters"
      CORS_ORIGIN: "http://localhost:3000,http://localhost:3001"
    volumes:
      - ./services/task-service:/app
      - /app/node_modules
      - /app/dist
    depends_on:
      task-db:
        condition: service_healthy
      redis:
        condition: service_healthy
      auth-service:
        condition: service_started
    restart: unless-stopped

  # Agregar frontend al compose
  task-frontend:
    build:
      context: ./frontend/task-frontend
      dockerfile: Dockerfile.dev
    container_name: task-manager-frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_AUTH_SERVICE_URL_DEV: "http://localhost:3001/api/v1"
      NEXT_PUBLIC_TASK_SERVICE_URL_DEV: "http://localhost:3002/api/v1"
    volumes:
      - ./frontend/task-frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - auth-service
      - task-service
    restart: unless-stopped