# ==============================================
# RENDER.COM DEPLOYMENT CONFIGURATION
# Auth Service - Task Manager
# ==============================================

services:
  # Auth Service Web Application
  - type: web
    name: task-manager-auth
    runtime: node
    region: oregon  # Cambia según tu preferencia
    plan: starter   # Escala según necesidades
    
    # Build Configuration
    buildCommand: |
      npm ci &&
      npm run build &&
      npx prisma generate &&
      npx prisma migrate deploy
    
    startCommand: npm run start:prod
    
    # Health Check
    healthCheckPath: /api/v1/health
    
    # Auto-deploy from main branch
    autoDeploy: true
    branch: main
    
    # Environment Variables
    envVars:
      - key: NODE_ENV
        value: production
        
      - key: PORT
        value: 3001
        
      - key: API_VERSION
        value: v1
        
      # Database connection (se conectará automáticamente)
      - key: DATABASE_URL
        fromDatabase:
          name: task-manager-auth-db
          property: connectionString
          
      # Redis connection (configurar manualmente)
      - key: REDIS_URL
        value: redis://your-redis-instance:6379
        
      - key: REDIS_PREFIX
        value: auth:
        
      # JWT Secrets (configurar en Render dashboard por seguridad)
      - key: JWT_SECRET
        generateValue: true  # Render generará automáticamente
        
      - key: REFRESH_TOKEN_SECRET
        generateValue: true
        
      - key: JWE_SECRET
        generateValue: true
        
      - key: JWT_EXPIRES_IN
        value: 15m
        
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 7d
        
      - key: JWT_ISSUER
        value: task-manager-auth
        
      # CORS - Actualizar con URLs reales
      - key: CORS_ORIGIN
        value: https://task-manager-frontend.render.com,https://task-manager-tasks.render.com
        
      # Security
      - key: HELMET_ENABLED
        value: true
        
      # Rate Limiting
      - key: RATE_LIMIT_ENABLED
        value: true
        
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
        
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
        
      # Logging
      - key: LOG_LEVEL
        value: info
        
      - key: LOG_PRETTY
        value: false  # Mejor para producción
        
      # Swagger
      - key: SWAGGER_ENABLED
        value: true

# Database Configuration
databases:
  - name: task-manager-auth-db
    databaseName: auth_db
    user: auth_user
    plan: starter  # Escala según necesidades
    region: oregon # Misma región que el servicio
    
    # Configuración de PostgreSQL
    postgresMajorVersion: 15
    
    # Backup automático
    ipAllowList:
      - source: 0.0.0.0/0  # Permitir acceso desde cualquier IP (configurar más restrictivo en producción)
        description: Allow all connections